ESTADO_GENERICO_DESHABILITADO = '0'
ESTADO_GENERICO_HABILITADO = '1'

ESTADO_GENERICO_CHOICES = (
    (ESTADO_GENERICO_DESHABILITADO, 'Deshabilitado'),
    (ESTADO_GENERICO_HABILITADO, 'Habilitado'),
)